name: Sentinel

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        spark-version: [2.4.4, 2.4.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Set up Spark ${{ matrix.spark-version }}
      run: |
        echo `python -V`
        echo ${{ matrix.spark-version }}
    - name: Check
      run: |
        echo `python -V`
        echo ${{ matrix.spark-version }}

