name: Sentinel

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check HBase available
        run: |
          mkdir toto
          touch toto/test.sh
      - name: Check Kafka available
        run: |
          mkdir tutu
          touch tutu/test.sh
      - name: Check Spark available
        run: |
          mkdir titi
          touch titi/test.sh
  test-suite:
    needs: setup
    runs-on: ubuntu-latest
    env:
      FINK_HOME: `echo $GITHUB_WORKSPACE`
    strategy:
      matrix:
        python-version: [3.7]
        spark-version: [2.4.4, 2.4.7]
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Step1.1
      run: |
        echo `python -V`
        echo ${{ matrix.spark-version }}
        echo $FINK_HOME
        echo env.FINK_HOME
  clean:
    needs: test-suite
    runs-on: ubuntu-latest
    steps:
      - name: final
        run: |
          echo `python -V`
          echo ${{ matrix.spark-version }}
