name: Sentinel

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    strategy:
      matrix:
        python-version: [3.6, 3.7]
        spark-version: [2.4.4, 2.4.7]
    runs-on: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Spark ${{ matrix.spark-version }}
      env:
        SPARK_VERSION:  ${{ matrix.spark-version }}
      run: |
        echo `python -V`
        echo $SPARK_VERSION
    - name: Check
      run: |
        echo `python -V`
        echo $SPARK_VERSION

